#!/usr/bin/env php
<?php

define('APP_PATH', __DIR__ . '/application/');
define('RUNTIME_PATH', __DIR__ . '/runtime/');
define('SWOOLE_JOBS_ROOT_PATH', __DIR__);
date_default_timezone_set('Asia/Shanghai');

// ThinkPHP 引导文件
require SWOOLE_JOBS_ROOT_PATH . '/thinkphp/base.php';
require SWOOLE_JOBS_ROOT_PATH . '/vendor/autoload.php';
$config  = require_once APP_PATH . 'config.php';
$console = new \Kcloze\Jobs\Console($config['queue']);

$console->run();
